Add order to env labels
Tknika/iombian-services-marketplace pull request #27
Opened 2024-06-27 08:21 UTC by aitorcas23

Add an order parameter to the env labels depending on the order on which the env labels appear in the docker compose file.
If one env label appears before another, that label will appear before the other in the IoMBian configurator envs form.

2024-07-08 07:45 UTC, bodiroga requested changes
@aitorcas23 Una pequeña sugerencia, no sé si te animas a cambiarlo 😉

2024-07-08 07:45 UTC, bodiroga commented on .github/scripts/parse_labels.py
>      for service in services:
En python se puede usar ```enumerate``` para obtener el índice en un bucle sin tener que crear una variable auxiliar fuera del mismo:

```suggestion
    for env_order, service in enumerate(services):
```

¿Te animas a cambiarlo o lo dejo así?

2024-07-09 09:19 UTC, aitorcas23 commented on .github/scripts/parse_labels.py
>      for service in services:
Lo que yo quiero hacer no es enumerar los servicios, quiero contar los grupos de labels de cada variable de entorno.
Por eso, cada vez que un label no se encuentra en `service_labels["envs"]`, se suma uno al contador.
Si aplicara ese cambio, el orden de cada label no se aplicaría bien.

2024-07-10 07:25 UTC, bodiroga commented on .github/scripts/parse_labels.py
>      for service in services:
Ok, perdona @aitorcas23, con el diff de la interfaz web no había visto todos los "if"s intermedios que hay en el código, sólo me había fijado en lo que se muestra aquí. Tienes razón 😉

2024-07-10 07:25 UTC, bodiroga approved these changes
LGTM!

2024-07-10 07:25 UTC, merged